# Generated by Django 3.2.16 on 2022-11-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20210924_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrezveznoImeProblema',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem')),
            ],
            options={
                'verbose_name': 'Množice / brezvezen problem',
            },
            bases=('problems.problem',),
        ),
    ]
